// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDaq6DEjQu09SNJAcBqGTotx9qNunAq0o',
    appId: '1:688739015905:web:cf5121a0cc0cdf5748eba0',
    messagingSenderId: '688739015905',
    projectId: 'edconnex-7e406',
    authDomain: 'edconnex-7e406.firebaseapp.com',
    storageBucket: 'edconnex-7e406.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7oynVaLn8e_BS863oQzsQB1OQgODz38Y',
    appId: '1:688739015905:android:7c4517f65ef8e65148eba0',
    messagingSenderId: '688739015905',
    projectId: 'edconnex-7e406',
    storageBucket: 'edconnex-7e406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuHx7i6QGPnLDzG_Zc3k2iqz5Dy5pJMs',
    appId: '1:688739015905:ios:580c0f3b7070f1e748eba0',
    messagingSenderId: '688739015905',
    projectId: 'edconnex-7e406',
    storageBucket: 'edconnex-7e406.firebasestorage.app',
    iosBundleId: 'com.example.edconnex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDaq6DEjQu09SNJAcBqGTotx9qNunAq0o',
    appId: '1:688739015905:web:a24335e7cca1d31e48eba0',
    messagingSenderId: '688739015905',
    projectId: 'edconnex-7e406',
    authDomain: 'edconnex-7e406.firebaseapp.com',
    storageBucket: 'edconnex-7e406.firebasestorage.app',
  );
}
