// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHOquuYes0TOh7J21a59L8nVNc2wsBu8',
    appId: '1:612421330214:web:b999b17d9665fed1fc4de7',
    messagingSenderId: '612421330214',
    projectId: 'edconnex-6dcdc',
    authDomain: 'edconnex-6dcdc.firebaseapp.com',
    storageBucket: 'edconnex-6dcdc.firebasestorage.app',
    measurementId: 'G-D1GSZTHKMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNNnegByymsrENkx--6a8XrmFawRK1sA',
    appId: '1:612421330214:android:957e0f6661613f31fc4de7',
    messagingSenderId: '612421330214',
    projectId: 'edconnex-6dcdc',
    storageBucket: 'edconnex-6dcdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPgfn8DWILdt0s3nkkPbY7vIaK4U25eCc',
    appId: '1:612421330214:ios:f030f61925468690fc4de7',
    messagingSenderId: '612421330214',
    projectId: 'edconnex-6dcdc',
    storageBucket: 'edconnex-6dcdc.firebasestorage.app',
    iosBundleId: 'com.example.edconnex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPgfn8DWILdt0s3nkkPbY7vIaK4U25eCc',
    appId: '1:612421330214:ios:f030f61925468690fc4de7',
    messagingSenderId: '612421330214',
    projectId: 'edconnex-6dcdc',
    storageBucket: 'edconnex-6dcdc.firebasestorage.app',
    iosBundleId: 'com.example.edconnex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcHOquuYes0TOh7J21a59L8nVNc2wsBu8',
    appId: '1:612421330214:web:88895abcc16b854bfc4de7',
    messagingSenderId: '612421330214',
    projectId: 'edconnex-6dcdc',
    authDomain: 'edconnex-6dcdc.firebaseapp.com',
    storageBucket: 'edconnex-6dcdc.firebasestorage.app',
    measurementId: 'G-YB7XL79N9R',
  );
}
